---
# - name: Install Docker prerequisites
#   ansible.builtin.package:
#     name: "{{ item }}"
#     state: present
#   loop:
#     - apt-transport-https
#     - ca-certificates
#     - curl
#     - software-properties-common
#   tags:
#     - docker

# - name: Add Docker's official GPG key
#   ansible.builtin.apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     state: present
#   tags:
#     - docker

# - name: Verify that we have the key with the fingerprint
#   ansible.builtin.apt_key:
#     id: 0EBFCD88
#     state: present
#   tags:
#     - docker

# - name: Set up the stable repository
#   ansible.builtin.apt_repository:
#     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
#     state: present
#     update_cache: yes
#   tags:
#     - docker

# - name: Update apt packages
#   ansible.builtin.apt:
#     update_cache: yes
#   tags:
#     - docker

# - name: Install Docker
#   ansible.builtin.apt:
#     name: docker-ce
#     state: present
#     update_cache: yes
#   tags:
#     - docker

# - name: Add remote "thed" user to "docker" group
#   ansible.builtin.user:
#     name: "thed"
#     group: docker
#     append: yes
#   tags:
#     - docker

- name: Install docker-compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.28.1/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
  tags:
    - docker